# slowfast_16x8_resnet101_kinetics400


CONFIG:
  TRAIN:
    EPOCH_NUM: 100
    BATCH_SIZE: 32
    LR: 0.005
    MOMENTUM: 0.9
    W_DECAY: 1e-5

  VAL:
    FREQ: 2
    BATCH_SIZE: 8

  DATA:
    TRAIN_ANNO_PATH: '/data/UCF101/train_rgb_split1.txt'
    VAL_ANNO_PATH: '/data/UCF101/val_rgb_split1.txt'
    TRAIN_DATA_PATH: '/data/UCF101/frames/'
    VAL_DATA_PATH:  '/data/UCF101/frames/'


  MODEL:
    NAME: 'slowfast_16x8_resnet101_kinetics400'
    PRETRAINED: False


